### ISSUE TITLE
[BUG] electronic details on readme

### ISSUE THREAD

**Issue by nicolas-rabault** [Luos-io/Examples#10]
**Describe the bug**
The readme on section electronics of examples is not really usefull. we should have a link to a more detailed documentation(not necessarly the main page) and add a link to the actual library folder.
![Capture d’écran 2020-05-08 à 10 03 28](https://user-images.githubusercontent.com/9554146/81385342-77e31b80-9113-11ea-9395-b7020b3eb5a9.png)

**Comment by Emanuel-Allely** [comment]
There's a new readme with more details about electronics for examples.
