### ISSUE TITLE
[NEW FEATURE] 

### ISSUE THREAD

**Issue by Salem-Tho** [Luos-io/Examples#106]
**What feature would you like to be included in Luos?**
In Luos we have Luos CMD : GET and SET!
this 2 cmd was created for the pipe to set or get unknow value of the data.

We need to change this 2 cmd set and get by only one call unknow and différenciate a set or a get with the size of the data:
UNKNOW CMD -> size 0 = GET
UNKNOW CMD -> size ! 0 = SET

in pipe SET and Get  must be replace by UNKNOW cmd! 
 
In case of localhost gate set directly in pipe buffer msg and send a cmd set with a size at 0 To drain the the pipe buffer!
this must be remove from gate and drain the the pipe buffer in the pipe loop

**Comment by JeromeGalan** [comment]
Done in 2.5.0 (currently in development)
