### ISSUE TITLE
[BUG] motor_mode_t size clash after generic parameters implementation

### ISSUE THREAD

**Issue by fleborne** [Luos-io/Examples#40]
After https://github.com/Luos-io/Examples/commit/bfc2d421f522bb9477b674c1cd2d634e286aeffc, it seems that it became impossible to change the parameters of a Controller_Motor (and maybe other projects as well).

In fact, [this line](https://github.com/Luos-io/Examples/blob/master/Drivers/Controller_motor/controller_motor.c#L416) of controller_motor checks for a message of size 2, while the size of the message is set to 4 by the Gate ([here](https://github.com/Luos-io/Examples/blob/master/Apps/Gate/convert.c#L351)).

I'm not sure how to fix the problem while keeping generic parameters?

**Comment by nicolas-rabault** [comment]
Seem to be fixed on the latest release.
