### ISSUE TITLE
[BUG] Gate auto-update with big RTB

### ISSUE THREAD

**Issue by nicolas-rabault** [Luos-io/Examples#80]
**Describe the bug**
In version 2.0.1 (without end detection feature) 
After detection, Gate start to configure 11/21 motor auto-update. Then there is 37ms of void then a configuration of 21 auto-update.
We should only have 21 auto-update directly after detection.

<img width="996" alt="Capture d’écran 2021-12-08 à 12 45 30" src="https://user-images.githubusercontent.com/9554146/145203239-1d9881ba-aca0-4c25-a09b-53626f5b4fe8.png">

<img width="809" alt="Capture d’écran 2021-12-08 à 12 45 43" src="https://user-images.githubusercontent.com/9554146/145203259-a268b60b-4ec9-46d2-a6c8-079cd0be6c6d.png">

**Network configuration**
- 21 motor boards
- Revision 2.0.1 of Luos

**Comment by BiliouriV** [comment]
@nicolas-rabault I have already fixed this after the new detection method.

**Comment by nicolas-rabault** [comment]
OK so this is already fixed in 2.1.0. 👍
